$terminal = kitty
$apps-manager = wofi --show drun

# Default monitor config
monitor = Virtual-1, 1920x1080, 0x0, 1

# Execute once hyprland start
exec-once = $HOME/.config/hypr/scripts/wallpaper.sh

# kill hyprland
bind = SUPER, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit

# kill active window
bind = SUPER, Q, killactive

# open terminal
bind = SUPER, RETURN, exec, $terminal

# open apps-manager
bind = SUPER, SPACE, exec, $apps-manager

# move window focus (up, down, left, right)
bind = SUPER, up, movefocus, u
bind = SUPER, down, movefocus, d
bind = SUPER, left, movefocus, l
bind = SUPER, right, movefocus, r

# move window (up, down, left, right)
bind = SUPER SHIFT, up, movewindow, u
bind = SUPER SHIFT, down, movewindow, d
bind = SUPER SHIFT, left, movewindow, l
bind = SUPER SHIFT, right, movewindow, r